defaults:
  - _self_
  - model: small
  - training: size_64
  - group: Swin

ngpu: 2
work_dir: null

rrdb:
  learning_rate: 3e-4
  cond_channel: 4
  num_feature: 32

evaluation:
  batch_size: 16
  num_samples: 5000
  fid: False
  sr: True
  ref: ./static/cifar10-32x32.npz

data:
  augmentation: false
  dataset_path: /bigpool/homes/yeyun/projects/PyramidDiffusionModel/datasets
  imresize_method: 'bilinear'

hydra:
  run:
    dir: exp_local/${group.type}/${training.dataset}/${now:%Y.%m.%d}/
  sweep:
    dir: exp/${group.type}/${training.dataset}/${now:%Y.%m.%d}/
    subdir: ${hydra.job.num}